name: flutter_application_restaraunt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  intl: ^0.20.2
  talker_flutter: ^4.7.2
  talker_dio_logger: ^4.7.1
  talker_bloc_logger: ^4.7.2
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  auto_route: ^7.8.4
  flutter_dotenv: ^5.2.1

  yandex_mapkit: ^4.1.0
  geolocator: ^13.0.4

  email_validator: '^3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svg/